name: ezanimation
description: Easy Animations - No Controllers, No Tickers, Only the necessary parts.
version: 0.3.0
author: Deven Joshi <deven9852@gmail.com>
homepage: https://www.github.com/deven98/ez_animation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
